version: '3'
services:
  postgres:
    container_name: postgresDB
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  api:
    container_name: dev-pizza-api-container
    build: .
    restart: always
    image: dev-pizza-api
    ports:
      - "4000:4000"
    links:
      - postgres